version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

volumes:
  postgres_data: